version = 1
disable_existing_loggers = false

[root]
handlers = ['screen', 'file']
level = 'DEBUG'

[loggers."websockets.server"]
level = 'INFO'

[loggers."transitions"]
level = 'WARNING'

[loggers."ocpp"]
level = 'WARNING'

[formatters.simple]
format = "%(asctime)s [%(levelname)-8s] %(name)s - %(message)s"
datefmt = '%Y-%m-%d %H:%M:%S'

[handlers.file]
class = "logging.handlers.TimedRotatingFileHandler"
when = "midnight"
backupCount = 5
formatter = "simple"
level = "DEBUG"
filename = 'logs/ocpp-mqtt-bridge.log'

[handlers.screen]
class = "logging.StreamHandler"
formatter = "simple"
level = "DEBUG"
stream = "ext://sys.stdout"
