name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/build-push-action@v6.7.0
      with:
        tags: ghcr.io/intrinseca/ocpp-mqtt-bridge:$(date +%s)
        push: true
